from sympy import Matrix, Rational

# the use of Rational(1, 2) over 1/2 is used in order for sympy to keep our equations symbolic
configs = {}
TwoD = Matrix([[1, 1, -1, -1, 1, 1],
               [1, 1, 1, -1, -1, 1],
               [-1, 1, 1, 1, -1, 1],
               [-1, -1, 1, 1, 1, 1],
               [1, -1, -1, 1, 1, 1],
               [1, 1, 1, 1, 1, 1]])
D = Rational(1, 2) * TwoD
Dinv = D ** -1
s = Matrix([1, 0, 0, 0, 0, 0])
b = Matrix([Rational(1, 2), Rational(-1, 2), Rational(1, 2), Rational(1, 2), Rational(-1, 2), Rational(1, 2)])
f = Matrix([Rational(1, 2), 0, 0, Rational(-1, 2), 0, 0])

configs[1] = (D * s, f)
configs[2] = (Rational(1, 2) * D * D * s, f)
configs[3] = (s, f)
configs[4] = (Rational(1, 2) * D * s, f)
configs[5] = (Rational(1, 2) * s, f)
configs[6] = (Rational(1, 2) * Dinv * s, f)
configs[7] = (D * s, b)
configs[8] = (s, b)
configs[9] = (Dinv * s, b)
configs[10] = (Dinv * Dinv * s, b)
configs[11] = (D * s, s)
configs[12] = (s, s)
configs[13] = (Dinv * s, s)
configs[14] = (D * D * b, f)
configs[15] = (Rational(1, 2) * D * D * D * b, f)
configs[16] = (D * b, f)
configs[17] = (Rational(1, 2) * D * D * b, f)
configs[18] = (b, f)
configs[19] = (Rational(1, 2) * D * b, f)
configs[20] = (Rational(1, 2) * b, f)
configs[21] = (Rational(1, 2) * Dinv * b, f)
configs[22] = (D * D * b, b)
configs[23] = (D * b, b)
configs[24] = (b, b)
configs[25] = (Dinv * b, b)
configs[26] = (Dinv * Dinv * b, b)
configs[27] = (D * D * b, s)
configs[28] = (D * b, s)
configs[29] = (b, s)
configs[30] = (Dinv * b, s)
configs[31] = (2 * D * f, f)
configs[32] = (D * D * f, f)
configs[33] = (2 * f, f)
configs[34] = (D * f, f)
configs[35] = (2 * Dinv * f, f)
configs[36] = (f, f)
configs[37] = (Rational(1, 2) * D * f, f)
configs[38] = (Dinv * f, f)
configs[39] = (Rational(1, 2) * f, f)
configs[40] = (Dinv * Dinv * f, f)
configs[41] = (Rational(1, 2) * Dinv * f, f)
configs[42] = (2 * D * f, b)
configs[43] = (2 * f, b)
configs[44] = (2 * Dinv * f, b)
configs[45] = (f, b)
configs[46] = (2 * Dinv * Dinv * f, b)
configs[47] = (Dinv * f, b)
configs[48] = (2 * Dinv * Dinv * Dinv * f, b)
configs[49] = (Dinv * Dinv * f, b)
configs[50] = (2 * D * f, s)
configs[51] = (2 * f, s)
configs[52] = (2 * Dinv * f, s)
configs[53] = (f, s)
configs[54] = (2 * Dinv * Dinv * f, s)
configs[55] = (Dinv * f, s)
